BudgetCalculator/BudgetCalculator/Controllers/BudgetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BudgetCalculator.Models;
using DotNet.Highcharts.Options;
using DotNet.Highcharts.Helpers;

namespace BudgetCalculator.Controllers
{
    public class BudgetsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        
        // Global variables to be accessed throughout controller methods
        double globalTotalIncome = 0;
        double globalTotalCarExpenses = 0;
        double globalTotalHouseholdExpenses = 0;
        double globalTotalPersonalExpenses = 0;
        double globalTotalTravelExpenses = 0;
        double globalTotalUtilityBillExpenses = 0;
        double globalTotalExpenses = 0;
        double globalBudgetBalance = 0;
        
            
        // GET: Budgets
        public ActionResult Index()
        {
            var budgets = db.Budgets.Include(b => b.BudgetUser);
            return View(budgets.ToList());
        }

        // GET: Budgets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Budget budget = db.Budgets.Find(id);
            if (budget == null)
            {
                return HttpNotFound();
            }
            return View(budget);
        }

        // GET: Budgets/Create
        public ActionResult Create(int id)
        {
            //// initially have a Car with no electronic tag and price displayed
            //return View(new Vehicle { VehicleType = VehicleType.Car, HasETag = false });

            Budget b = new Budget();
            b.BudgetUserId = id;
            // ViewBag.BudgetUserId = new SelectList(db.BudgetUsers, "BudgetUserId", "LastName");
            return View(b);
        }

        // POST: Budgets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BudgetId,BudgetUserId,BudgetName,BudgetStartDate,BudgetEndDate")] Budget budget, int id)
        {
            budget.BudgetUserId = id;
            if (ModelState.IsValid)
            {
                db.Budgets.Add(budget);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BudgetUserId = new SelectList(db.BudgetUsers, "BudgetUserId", "LastName", budget.BudgetUserId);
            return View(budget);
        }

        // GET: Budgets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Budget budget = db.Budgets.Find(id);
            if (budget == null)
            {
                return HttpNotFound();
            }
            ViewBag.BudgetUserId = new SelectList(db.BudgetUsers, "BudgetUserId", "LastName", budget.BudgetUserId);
            return View(budget);
        }

        // POST: Budgets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BudgetId,BudgetUserId,BudgetName,BudgetStartDate,BudgetEndDate")] Budget budget)
        {
            if (ModelState.IsValid)
            {
                db.Entry(budget).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BudgetUserId = new SelectList(db.BudgetUsers, "BudgetUserId", "LastName", budget.BudgetUserId);
            return View(budget);
        }

        // GET: Budgets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Budget budget = db.Budgets.Find(id);
            if (budget == null)
            {
                return HttpNotFound();
            }
            return View(budget);
        }

        // POST: Budgets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Budget budget = db.Budgets.Find(id);
            db.Budgets.Remove(budget);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // Budget Summary View
        public ActionResult Summary(int? id)
        {
            // Calculation here
            Budget b = new Budget();
            b = db.Budgets.Where(p => p.BudgetId == id).SingleOrDefault();

            // ***************** INCOME *****************
            Income i = new Income();
            i = db.Incomes.Where(inc => inc.BudgetId == id).SingleOrDefault();

            double totalIncome = 0;

            // ---------- PrimaryIncomeAmount ----------
            ViewBag.PrimaryIncomeAmount = i.PrimaryIncomeAmount;
            if (i.PrimaryIncomeAmount == null)
            {
                // set initial amount to zero
                i.PrimaryIncomeAmount = 0;
                ViewBag.PrimaryIncomeAmount = i.PrimaryIncomeAmount;
            }
            else
            {
                // otherwise set AdditionalIncomeAmount to user input
                ViewBag.PrimaryIncomeAmount = i.PrimaryIncomeAmount;
            }

            // ---------- AdditionalIncomeAmount ----------
            // if AdditionalIncomeAmount is NULL
            ViewBag.AdditionalIncomeAmount = i.AdditionalIncomeAmount;
            if (i.AdditionalIncomeAmount == null)
            {
                // set initial amount to zero
                i.AdditionalIncomeAmount = 0;
                ViewBag.AdditionalIncomeAmount = i.AdditionalIncomeAmount;
            }
            else
            {
                // otherwise set AdditionalIncomeAmount to user input
                ViewBag.AdditionalIncomeAmount = i.AdditionalIncomeAmount;
            }

            // Calculate totalIncome (PrimaryIncomeAmount + AdditionalIncomeAmount)
            totalIncome = (double)i.PrimaryIncomeAmount; // set totalIncome = PrimaryIncome
            if (i.AdditionalIncomeAmount != null)
            {
                // If AdditionalIncomeAmount, execute
                totalIncome = (double)i.PrimaryIncomeAmount + (double)i.AdditionalIncomeAmount;
            }
            ViewBag.TotalIncome = totalIncome;
            globalTotalIncome = totalIncome;
            //-----------------------------------------------------------------------------------------------
            //-----------------------------------------------------------------------------------------------
            //-----------------------------------------------------------------------------------------------

            // ***************** CAR EXPENSES *****************
            CarExpense c = new CarExpense();
            c = db.CarExpenses.Where(car => car.BudgetId == id).SingleOrDefault();

            double totalCarExpenses = 0;

            // ---------- CarTax ----------
            ViewBag.CarTax = c.CarTax;
            if (c.CarTax == null)
            {
                // set initial amount to zero
                c.CarTax = 0;
                ViewBag.CarTax = c.CarTax;
            }
            else
            {
                // otherwise set CarTax to user input
                ViewBag.CarTax = c.CarTax;
            }

            // ---------- CarInsurance ----------
            ViewBag.CarInsurance = c.CarInsurance;
            if (c.CarInsurance == null)
            {
                // set initial amount to zero
                c.CarInsurance = 0;
                ViewBag.CarInsurance = c.CarInsurance;
            }
            else
            {
                // otherwise set CarCarInsurance to user input
                ViewBag.CarCarInsurance = c.CarInsurance;
            }

            // ---------- Maintenance ----------
            ViewBag.Maintenance = c.Maintenance;
            if (c.Maintenance == null)
            {
                // set initial amount to zero
                c.Maintenance = 0;
                ViewBag.Maintenance = c.Maintenance;
            }
            else
            {
                // otherwise set Maintenance to user input
                ViewBag.Maintenance = c.Maintenance;
            }

            // ---------- FuelAmount ----------
            ViewBag.FuelAmount = c.FuelAmount;
            if (c.FuelAmount == null)
            {
                // set initial amount to zero
                c.FuelAmount = 0;
                ViewBag.FuelAmount = c.FuelAmount;
            }
            else
            {
                // otherwise set FuelAmount to user input
                ViewBag.FuelAmount = c.FuelAmount;
            }

            // ---------- NctAmount ----------
            ViewBag.NctAmount = c.NctAmount;
            if (c.NctAmount == null)
            {
                // set initial amount to zero
                c.NctAmount = 0;
                ViewBag.NctAmount = c.NctAmount;
            }
            else
            {
                // otherwise set NctAmount to user input
                ViewBag.NctAmount = c.NctAmount;
            }


BudgetCalculator/BudgetCalculator/Controllers/IncomesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BudgetCalculator.Models;

namespace BudgetCalculator.Controllers
{
    public class IncomesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Incomes
        public ActionResult Index()
        {
            var incomes = db.Incomes.Include(i => i.Budget);
            return View(incomes.ToList());
        }

        // GET: Incomes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Income income = db.Incomes.Find(id);
            if (income == null)
            {
                return HttpNotFound();
            }
            return View(income);
        }

        // GET: Incomes/Create
        public ActionResult Create(int id) // int id
        {
            // foreign key id attribute
            Income inc = new Income();
            inc.BudgetId = id;
            // ViewBag.BudgetId = new SelectList(db.Budgets, "BudgetId", "BudgetName");
            return View(inc); // inc
        }

        // POST: Incomes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IncomeId,PrimaryIncomeAmount,AdditionalIncomeAmount,TotalIncome,BudgetId")] Income income, int id) // , int id
        {
            // foreign key id attribute
            income.BudgetId = id;
            if (ModelState.IsValid)
            {
                db.Incomes.Add(income);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BudgetId = new SelectList(db.Budgets, "BudgetId", "BudgetName", income.BudgetId);
            return View(income);
        }

        // GET: Incomes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Income income = db.Incomes.Find(id);
            if (income == null)
            {
                return HttpNotFound();
            }
            ViewBag.BudgetId = new SelectList(db.Budgets, "BudgetId", "BudgetName", income.BudgetId);
            return View(income);
        }

        // POST: Incomes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IncomeId,PrimaryIncomeAmount,AdditionalIncomeAmount,TotalIncome,BudgetId")] Income income)
        {
            if (ModelState.IsValid)
            {
                db.Entry(income).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BudgetId = new SelectList(db.Budgets, "BudgetId", "BudgetName", income.BudgetId);
            return View(income);
        }

        // GET: Incomes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Income income = db.Incomes.Find(id);
            if (income == null)
            {
                return HttpNotFound();
            }
            return View(income);
        }

        // POST: Incomes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Income income = db.Incomes.Find(id);
            db.Incomes.Remove(income);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BudgetCalculator/BudgetCalculator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Monthly Budget Calculator</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
                    @*<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">*@
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Budget Calculator", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>

            @*<div class="navbar-collapse collapse">*@
            <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-2">
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("Home", "Index", "Home")</li>

                    <li>@Html.ActionLink("Users", "Index", "BudgetUsers")</li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" role="button" aria-expanded="false"
                           href="#" data-toggle="dropdown">My Budgets<span class="caret"></span></a>

                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("View Budgets", "Index", "Budgets")</li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" role="button" aria-expanded="false"
                           href="#" data-toggle="dropdown">Income<span class="caret"></span></a>

                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Add Income", "Index", "Incomes")</li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" role="button" aria-expanded="false"
                           href="#" data-toggle="dropdown">Expenses<span class="caret"></span></a>

                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Car", "Index", "CarExpenses")</li>
                            <li>@Html.ActionLink("Household", "Index", "HouseholdExpenses")</li>
                            <li>@Html.ActionLink("Personal", "Index", "PersonalExpenses")</li>
                            <li>@Html.ActionLink("Travel", "Index", "TravelExpenses")</li>
                            <li>@Html.ActionLink("Utility Bills", "Index", "UtilityBillExpenses")</li>
                        </ul>
                    </li>
                    
                    @*<li class="dropdown">
                        <a class="dropdown-toggle" role="button" aria-expanded="false"
                           href="#" data-toggle="dropdown">Analysis<span class="caret"></span></a>

                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Budget Summary", "Summary", "Budgets")</li>
                            <li>@Html.ActionLink("Budget Forecast", "Forecast", "Budgets")</li>
                        </ul>
                    </li>*@
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year | Monthly Budget Calculator | Cliff Browne | @Html.ActionLink("Contact", "Contact", "Home")</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/Highcharts-4.0.1/js/highcharts-all.js"></script>
</body>
</html>