BudgetCalculator/BudgetCalculator/Models/BudgetUser.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;

namespace BudgetCalculator.Models
{
    public class BudgetUser
    {
        public int BudgetUserId { get; set; }

        [Required]
        [StringLength(50, ErrorMessage = "Last name cannot be longer than 50 characters.")]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required]
        [StringLength(50, ErrorMessage = "First name cannot be longer than 50 characters.")]
        [Column("FirstName")]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        // Concatenate last & first name to display users full name
        [Display(Name = "Full Name")]
        public string FullName
        {
            get
            {
                return FirstName + " " + LastName;
            }
        }

        // DOB is nullable (not 01/01/0001 at launch)
        [Required]
        [DataType(DataType.Date, ErrorMessage = "Please enter a valid date in the format dd/mm/yyyy")]
        [Display(Name = "D.O.B")]
        public DateTime? DateOfBirth { get; set; }

        [Required(ErrorMessage = "Address Line 1 is Mandatory")]
        [StringLength(50, ErrorMessage = "Address Line 1 cannot be more than 50 characters.")]
        [Display(Name = "Address Line 1")]
        public String AddressLine1 { get; set; }

        [StringLength(50, ErrorMessage = "Address Line 2 cannot be more than 50 characters.")]
        [Display(Name = "Address Line 2")]
        public String AddressLine2 { get; set; }

        [StringLength(50, ErrorMessage = "Town cannot be more than 50 characters.")]
        [Display(Name = "Town")]
        public String Town { get; set; }

        [StringLength(50, ErrorMessage = "County cannot be more than 50 characters.")]
        [Display(Name = "County")]
        public String County { get; set; }

        [StringLength(50, ErrorMessage = "Country cannot be more than 50 characters.")]
        [Display(Name = "Country")]
        public String Country { get; set; }

        [Display(Name = "Post Code")]
        public String PostCode { get; set; }

        [Required(ErrorMessage = "Contact Number is Mandatory")]
        [Display(Name = "Contact No.")]
        public String ContactNo { get; set; }

        // check that the e-mail address is of the correct form (not that it actually exists)
        private bool isEmail(string inputEmail)
        {
            Regex re = new Regex(@"^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$",
                          RegexOptions.IgnoreCase);
            return re.IsMatch(inputEmail);
        }
        //public Budget budget {get;set}
        public virtual ICollection<Budget> Budgets { get; set; }
    }
}

BudgetCalculator/BudgetCalculator/Controllers/BudgetUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BudgetCalculator.Models;

namespace BudgetCalculator.Controllers
{
    public class BudgetUsersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: BudgetUsers
        public ActionResult Index()
        {
            return View(db.BudgetUsers.ToList());
        }

        // GET: BudgetUsers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BudgetUser budgetUser = db.BudgetUsers.Find(id);
            if (budgetUser == null)
            {
                return HttpNotFound();
            }
            return View(budgetUser);
        }

        // GET: BudgetUsers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BudgetUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BudgetUserId,LastName,FirstName,DateOfBirth,AddressLine1,AddressLine2,Town,County,Country,PostCode,ContactNo")] BudgetUser budgetUser)
        {
            if (ModelState.IsValid)
            {
                db.BudgetUsers.Add(budgetUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(budgetUser);
        }

        // GET: BudgetUsers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BudgetUser budgetUser = db.BudgetUsers.Find(id);
            if (budgetUser == null)
            {
                return HttpNotFound();
            }
            return View(budgetUser);
        }

        // POST: BudgetUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BudgetUserId,LastName,FirstName,DateOfBirth,AddressLine1,AddressLine2,Town,County,Country,PostCode,ContactNo")] BudgetUser budgetUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(budgetUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(budgetUser);
        }

        // GET: BudgetUsers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BudgetUser budgetUser = db.BudgetUsers.Find(id);
            if (budgetUser == null)
            {
                return HttpNotFound();
            }
            return View(budgetUser);
        }

        // POST: BudgetUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BudgetUser budgetUser = db.BudgetUsers.Find(id);
            db.BudgetUsers.Remove(budgetUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BudgetCalculator/BudgetCalculator/Controllers/BudgetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BudgetCalculator.Models;
using DotNet.Highcharts.Options;
using DotNet.Highcharts.Helpers;

namespace BudgetCalculator.Controllers
{
    public class BudgetsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        
        // Global variables to be accessed throughout controller methods
        double globalTotalIncome = 0;
        double globalTotalCarExpenses = 0;
        double globalTotalHouseholdExpenses = 0;
        double globalTotalPersonalExpenses = 0;
        double globalTotalTravelExpenses = 0;
        double globalTotalUtilityBillExpenses = 0;
        double globalTotalExpenses = 0;
        double globalBudgetBalance = 0;
        
            
        // GET: Budgets
        public ActionResult Index()
        {
            var budgets = db.Budgets.Include(b => b.BudgetUser);
            return View(budgets.ToList());
        }

        // GET: Budgets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Budget budget = db.Budgets.Find(id);
            if (budget == null)
            {
                return HttpNotFound();
            }
            return View(budget);
        }

        // GET: Budgets/Create
        public ActionResult Create(int id)
        {
            //// initially have a Car with no electronic tag and price displayed
            //return View(new Vehicle { VehicleType = VehicleType.Car, HasETag = false });

            Budget b = new Budget();
            b.BudgetUserId = id;
            // ViewBag.BudgetUserId = new SelectList(db.BudgetUsers, "BudgetUserId", "LastName");
            return View(b);
        }

        // POST: Budgets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BudgetId,BudgetUserId,BudgetName,BudgetStartDate,BudgetEndDate")] Budget budget, int id)
        {
            budget.BudgetUserId = id;
            if (ModelState.IsValid)
            {
                db.Budgets.Add(budget);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BudgetUserId = new SelectList(db.BudgetUsers, "BudgetUserId", "LastName", budget.BudgetUserId);
            return View(budget);
        }

        // GET: Budgets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Budget budget = db.Budgets.Find(id);
            if (budget == null)
            {
                return HttpNotFound();
            }
            ViewBag.BudgetUserId = new SelectList(db.BudgetUsers, "BudgetUserId", "LastName", budget.BudgetUserId);
            return View(budget);
        }

        // POST: Budgets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BudgetId,BudgetUserId,BudgetName,BudgetStartDate,BudgetEndDate")] Budget budget)
        {
            if (ModelState.IsValid)
            {
                db.Entry(budget).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BudgetUserId = new SelectList(db.BudgetUsers, "BudgetUserId", "LastName", budget.BudgetUserId);
            return View(budget);
        }

        // GET: Budgets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Budget budget = db.Budgets.Find(id);
            if (budget == null)
            {
                return HttpNotFound();
            }
            return View(budget);
        }

        // POST: Budgets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Budget budget = db.Budgets.Find(id);
            db.Budgets.Remove(budget);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // Budget Summary View
        public ActionResult Summary(int? id)
        {
            // Calculation here
            Budget b = new Budget();
            b = db.Budgets.Where(p => p.BudgetId == id).SingleOrDefault();

            // ***************** INCOME *****************
            Income i = new Income();
            i = db.Incomes.Where(inc => inc.BudgetId == id).SingleOrDefault();

            double totalIncome = 0;

            // ---------- PrimaryIncomeAmount ----------
            ViewBag.PrimaryIncomeAmount = i.PrimaryIncomeAmount;
            if (i.PrimaryIncomeAmount == null)
            {
                // set initial amount to zero
                i.PrimaryIncomeAmount = 0;
                ViewBag.PrimaryIncomeAmount = i.PrimaryIncomeAmount;
            }
            else
            {
                // otherwise set AdditionalIncomeAmount to user input
                ViewBag.PrimaryIncomeAmount = i.PrimaryIncomeAmount;
            }

            // ---------- AdditionalIncomeAmount ----------
            // if AdditionalIncomeAmount is NULL
            ViewBag.AdditionalIncomeAmount = i.AdditionalIncomeAmount;
            if (i.AdditionalIncomeAmount == null)
            {
                // set initial amount to zero
                i.AdditionalIncomeAmount = 0;
                ViewBag.AdditionalIncomeAmount = i.AdditionalIncomeAmount;
            }
            else
            {
                // otherwise set AdditionalIncomeAmount to user input
                ViewBag.AdditionalIncomeAmount = i.AdditionalIncomeAmount;
            }

            // Calculate totalIncome (PrimaryIncomeAmount + AdditionalIncomeAmount)
            totalIncome = (double)i.PrimaryIncomeAmount; // set totalIncome = PrimaryIncome
            if (i.AdditionalIncomeAmount != null)
            {
                // If AdditionalIncomeAmount, execute
                totalIncome = (double)i.PrimaryIncomeAmount + (double)i.AdditionalIncomeAmount;
            }
            ViewBag.TotalIncome = totalIncome;
            globalTotalIncome = totalIncome;
            //-----------------------------------------------------------------------------------------------
            //-----------------------------------------------------------------------------------------------
            //-----------------------------------------------------------------------------------------------

            // ***************** CAR EXPENSES *****************
            CarExpense c = new CarExpense();
            c = db.CarExpenses.Where(car => car.BudgetId == id).SingleOrDefault();

            double totalCarExpenses = 0;

            // ---------- CarTax ----------
            ViewBag.CarTax = c.CarTax;
            if (c.CarTax == null)
            {
                // set initial amount to zero
                c.CarTax = 0;
                ViewBag.CarTax = c.CarTax;
            }
            else
            {
                // otherwise set CarTax to user input
                ViewBag.CarTax = c.CarTax;
            }

            // ---------- CarInsurance ----------
            ViewBag.CarInsurance = c.CarInsurance;
            if (c.CarInsurance == null)
            {
                // set initial amount to zero
                c.CarInsurance = 0;
                ViewBag.CarInsurance = c.CarInsurance;
            }
            else
            {
                // otherwise set CarCarInsurance to user input
                ViewBag.CarCarInsurance = c.CarInsurance;
            }

            // ---------- Maintenance ----------
            ViewBag.Maintenance = c.Maintenance;
            if (c.Maintenance == null)
            {
                // set initial amount to zero
                c.Maintenance = 0;
                ViewBag.Maintenance = c.Maintenance;
            }
            else
            {
                // otherwise set Maintenance to user input
                ViewBag.Maintenance = c.Maintenance;
            }

            // ---------- FuelAmount ----------
            ViewBag.FuelAmount = c.FuelAmount;
            if (c.FuelAmount == null)
            {
                // set initial amount to zero
                c.FuelAmount = 0;
                ViewBag.FuelAmount = c.FuelAmount;
            }
            else
            {
                // otherwise set FuelAmount to user input
                ViewBag.FuelAmount = c.FuelAmount;
            }

            // ---------- NctAmount ----------
            ViewBag.NctAmount = c.NctAmount;
            if (c.NctAmount == null)
            {
                // set initial amount to zero
                c.NctAmount = 0;
                ViewBag.NctAmount = c.NctAmount;
            }
            else
            {
                // otherwise set NctAmount to user input
                ViewBag.NctAmount = c.NctAmount;
            }


BudgetCalculator/BudgetCalculator/Views/BudgetUsers/Delete.cshtml
@model BudgetCalculator.Models.BudgetUser

@{
    ViewBag.Title = "Delete";
}
<p>
    <br />
    <a class="btn btn-primary btn-xs" @Html.ActionLink("Home", "Index", "Home")</a>
    <a class="btn btn-primary btn-xs" @Html.ActionLink("Users", "Index", "BudgetUsers")</a>
    @*@Html.ActionLink("Home", "Index", "Home") |
    @Html.ActionLink("Users", "Index", "BudgetUsers")*@
</p>
<h3>Delete User</h3>

<div>
    @*<hr />*@
    <dl class="dl-horizontal" style="text-align:left">
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressLine1)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AddressLine1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressLine2)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AddressLine2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Town)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Town)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.County)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.County)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PostCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactNo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ContactNo)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <h5>Click Delete User button to remove user.</h5>
        <div class="form-actions no-color">
            <input type="submit" value="Delete User" class="btn btn-danger" />
        </div>
    }
</div>

BudgetCalculator/BudgetCalculator/Views/BudgetUsers/Details.cshtml
@model BudgetCalculator.Models.BudgetUser

@{
    ViewBag.Title = "Details";
}
<p>
    <br />
    <a class="btn btn-primary btn-xs" @Html.ActionLink("Home", "Index", "Home")</a>
    <a class="btn btn-primary btn-xs" @Html.ActionLink("Users", "Index", "BudgetUsers")</a>
    @*@Html.ActionLink("Home", "Index", "Home") |
    @Html.ActionLink("Users", "Index", "BudgetUsers")*@
</p>
<h3>User Details</h3>

<div>
    @*<hr />*@
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressLine1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddressLine1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressLine2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddressLine2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Town)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Town)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.County)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.County)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactNo)
        </dd>
    </dl>
</div>

BudgetCalculator/BudgetCalculator/Views/BudgetUsers/Edit.cshtml
@model BudgetCalculator.Models.BudgetUser

@{
    ViewBag.Title = "Edit";
}
<p>
    <br />
    <a class="btn btn-primary btn-xs" @Html.ActionLink("Home", "Index", "Home")</a>
    <a class="btn btn-primary btn-xs" @Html.ActionLink("Users", "Index", "BudgetUsers")</a>
    @*@Html.ActionLink("Home", "Index", "Home") |
    @Html.ActionLink("Users", "Index", "BudgetUsers")*@
</p>
<h3>Edit User</h3>
<h5>Edit User details and click Save Changes button when done.</h5>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       @*<hr />*@
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BudgetUserId)

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressLine1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressLine1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressLine1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressLine2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressLine2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressLine2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Town, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Town, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Town, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.County, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.County, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.County, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save Changes" class="btn btn-success" />
            </div>
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}